---
- hosts: all
  become: yes
  vars_prompt:
    - name: mysql_password
      prompt: Write your password for the variable mysql_password
  vars:
    # Web about socket encryption https://dev.mysql.com/doc/refman/5.7/en/connection-options.html
    - mysql_socket_path: /var/run/mysqld/mysqld.sock
  tasks:
    - name: Update and upgrade existing packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt: 
        name: zip

    - name: Install and configure Apache
      include_role:
        name: install_and_configure_apache
        
    - name: Install MySQL
      include_role: 
        name: install_mysql
      vars:
        mysql_password: mysql_password
      
    # Beginning of steps taken of mysql_secure_installation
    - name: Execute make_mysql_secure role
      include_role:
        name: make_mysql_secure
    # End of MySQL securitize installation

    - name: Install PHP
      apt:
        name:
          - php
          - php-mysql
        state: latest
    
    - name: Copy PHP dummy file
      copy:
        src: info.php 
        dest: /var/www/html/info.php

    - name: Create database Wordpress
      mysql_db:
        name: wordpress_db
        state: present
        login_unix_socket: "{{ mysql_socket_path }}"

    - name: Create a user
      mysql_user:
        name: wp_user
        host: localhost
        state: present
        password: cool
        priv: 'wordpress_db.*:ALL'
        login_unix_socket: "{{ mysql_socket_path }}"
    
    - name: Download wordpress tar.gz
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Unzip downloaded tar.gz
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Change owner and permissions of wordpress directory
      file:
        path: /var/www/html/wordpress/
        owner: www-data
        group: www-data
        mode: '755'
        recurse: yes

    - name: Create directory
      file:
        path: /var/www/html/wordpress/wp-content/uploads
        state: directory
        owner: www-data
        group: www-data
        mode: '755'
        recurse: yes
      

  handlers:
    - name: Restart mysql service
      service:
        name: mysqld
        state: restarted