---
- hosts: all
  become: yes
  vars_prompt:
    - name: mysql_password
      prompt: Write your password for the variable mysql_password
  pre_tasks:
    - name: Update and upgrade existing packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt: 
        name: zip

  roles:
    - install_and_configure_apache
    - role: install_mysql
      vars:
        mysql_password: mysql_password
    - make_mysql_secure
    - install_and_configure_php
    - install_and_configure_wordpress      
