---
# tasks file for install_and_configure_apache
- name: Install Apache2 package
  apt: 
    name: apache2 
    state: latest
    update_cache: yes

- name: Configure Apache2 service
  service:
    name: apache2
    state: started