---
# tasks file for install_and_configure_wordpress
- name: Create database Wordpress
  mysql_db:
    name: wordpress_db
    state: present
    login_unix_socket: "{{ mysql_socket_path }}"

- name: Create a user
  mysql_user:
    name: wp_user
    host: localhost
    state: present
    password: cool
    priv: 'wordpress_db.*:ALL'
    login_unix_socket: "{{ mysql_socket_path }}"

- name: Download wordpress tar.gz
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Unzip downloaded tar.gz
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Change owner and permissions of wordpress directory
  file:
    path: /var/www/html/wordpress/
    owner: www-data
    group: www-data
    mode: '755'
    recurse: yes

- name: Create directory
  file:
    path: /var/www/html/wordpress/wp-content/uploads
    state: directory
    owner: www-data
    group: www-data
    mode: '755'
    recurse: yes